### ISSUE TITLE
Option for No Exceptions for Small Embedded Systems

### ISSUE THREAD

**Issue by bakerstu** [DuffsDevice/tiny-utf8#28]
I am using your library, and have a forked version here:

https://github.com/bakerstu/tiny-utf8

I use g++ and my project does not enable C++ exception handling.  I would not like to add exception handling because it increases the code size to be larger than I would like.  Therefore, I have "hacked" a fix into a branch noexcept that replaces the throw statements with assertions compatible with our project platform.

I acknowledge that this is not a portable fix, as is, and should not be accepted back as a pull request.  Therefore, I would like to propose an alternative solution that could possibly be accepted.

I want to replace your throw statements with an inline function call.  The inline function call should be ifndef guarded so that by default it throws the exception:

```
#if !defined(TINYUTF8_NOEXCEPT)
inline void tinyutf8_error(const char *what_arg)
{
    throw std::out_of_range(what_arg); 
}
#endif
```

If the user defines TINYUTF8_NOEXCEPT, then it is on them to provide an implementation of tinyutf8_error() that works for their purposes and platform.  This is an acceptable solution for my use case.

I'd like to get your thoughts on this, and if favorable, work on a pull request.

**Comment by DuffsDevice** [comment]
Hi Stuart,

I like your approach! After a bit of [googling](https://stackoverflow.com/questions/35571947/detect-at-compile-time-whether-exceptions-are-disabled) it seems that GCC will not define the macros `__EXCEPTIONS` as well as `__cpp_exceptions` when exceptions are disabled.
So my initial implementation out of the blue would be:
- determine the value of `TINYUTF8_NOEXCEPT` dynamically (with the above macros provided by gcc), if it has not yet been defined.
- Otherwise throw exceptions in `tinyutf8.h` , if `TINYUTF8_NOEXCEPT` has not been defined or has been defined to `0`.

What do you think? I look forward to hearing from you!

Cheers,
Jakob
