### ISSUE TITLE
incorrect string comparison behaviour after a substr operation

### ISSUE THREAD

**Issue by Apache-HB** [DuffsDevice/tiny-utf8#58]
```cpp
#include <tinyutf8/tinyutf8.h>
#include <stdio.h>
namespace utf8 = tiny_utf8;

int main() {
    utf8::string temp;

    for (char32_t c : { 13, 10, 104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 13, 10, 41, 34 }) {
        temp += c;
    }

    auto left = temp.substr(0, temp.length() - 2);

    utf8::string right = "\nhello world\n";

    printf("%s\n", left.c_str());
    printf("%s\n", right.c_str());

    printf("left: %ld, right: %ld\n", left.length(), right.length());

    if (left == right) {
        printf("strings were the same\n");
    } else {
        printf("strings were not the same\n");
    }
}
```
expected behaviour would be that both of these strings are the same length and are equal. yet `left.length() = 15` and `right.length() = 13` and `left != right`

**Comment by DuffsDevice** [comment]
Hi,
As far as I can see, the issue lies in `{ 13, 10, 104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 13, 10 }` being euql to `"\r\nhello world\r\n"`, **not** `"\nhello world\n"`. Character codes 10 and 13 stand for CARRIAGE-RETURN and NEWLINE. You might be a victim of [platform-dependent line ending](https://stackoverflow.com/questions/8033950/cross-platform-newline-confusion) ;)

Let me know, whether that helped you! (I will close this ticket for now)

Cheers,
Jakob
